### ISSUE TITLE
Unable to play specific roles once promoted to them

### ISSUE THREAD

**Issue by DreadedReborn** [Apollo-Community/ApolloStation#1019]
(Reported by DregonSteps, apologies if this is a dupe issue)
People cannot play as the roles they are promoted to once they gain said role.

**Comment by rjtwins** [comment]
While I need more data to be sure if there is a problem. Make sure to SAFE your char when you create it otherwise it will not ever be saved. Also your promotion may have been a temporary one (head promotions by HoP are temp). Or the round was non canon.
If you encounter this bug again please note down all the circumstances.
