### ISSUE TITLE
Need a way to deal with no id having criminals.

### ISSUE THREAD

**Issue by rjtwins** [Apollo-Community/ApolloStation#1142]
If a criminal ditches his ID somewhere unreachable (aka they jet it into space or something). There is NO WAY to convict them. This needs to change otherwise we end up putting people in solitary forever.

**Comment by Delnth** [comment]
You could use the forensic scanner to print the criminal's ID, and then use the fingerprint to make the sentence. 
Also, since the forensic scanner is issued to detectives only, an item that allow every sec staff to have the fingerprints of someone. (Maybe a tape and a reinforced white wood board. You what Im talking about right ? Heh.)
