### ISSUE TITLE
Antags and financial account console.

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#1176]
The financial account console in the hops office can be used to add massive amounts of funds to someones account. If done by a traitor they can get 100000 thalers/credits without problems and just keep order traitor items.
Also the same console can be used to check who is a traitor by watching how much money they have on their account. Because the money is out of range for the rest of the accounts. (traitors own way more money)

**Comment by InvidiaSH** [comment]
Definitely don't think this should be in. It's very exploitable.

**Comment by CakeQ** [comment]
Perhaps linking this to a "station funs account" similar to department accounts would be a solution

**Comment by nullbear** [comment]
The issue is it creates infinite money, and that it can be easily metagamed. 

I played around with this and for traitors I'm particular, it works quite oddly. 

My ID card is registered to Bob steins finance account. But Is labelled "sarah". Sarah also has a finances account which is the account used for purchasing traitor items.

-- I propose these as potential solutions:

Tie the ID to Sarahs account. Instead of the original characters account. Meaning using funds from the Id depletes traitor funds, not bobs funds.

Instead of loading up their account at round start, give them a wad of cash instead. This allows them to deposit it into their account as needed. And prevents early-game meta via the accounts console. It's their own fault if a watchful HoP notices them gaining loads of money somehow.

Having cold hard cash in your bag feels good.

**Comment by InvidiaSH** [comment]
I thought about this one some more, and I concluded that... To be honest. That console is like the bank. The bank decides how much money an account as (sort of). Changing the amount of money on your real life back account would sort of also allow you to make an infinite amount of money.

Closed as a feature.
