### ISSUE TITLE
atmos overlay

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#123]
when you fill a room with n2o or phoron the overlay prevents you from using anything on a tile.
And when you scrub the area it remains even though the phoron/n2o is gone

**Comment by JMMJ01** [comment]
If I remember correctly we had this same bug when Kwask changed Phoron a
while back. It did get fixed then.

**Comment by nullbear** [comment]
It was changed, but not ideally... The way atmos works, you can either make it so you can ONLY click the tile, or so that you can NEVER click the tile. You should make the overlay into a separate object that is unclickeable, guaranteeing that it covers everything, is unclickeable, and that the tile is clickeable.

**Comment by Awantje** [comment]
there is no reason to interact with the overlay

**Comment by Kwask** [comment]
Problem with making it into a separate object is that all of the atmospherics data is stored inside of the turf. That means that if you wanted to pass it to an entirely new object, you'd have to make a new object for every single tile on every z-level, and pass the data over from the turf constantly

It needs to be clarified whether this issue is that you can't use objects on a turf, or whether you can't use the turf itself.

**Comment by Awantje** [comment]
If the overlay is there for example in the engine room I cannot click a pump to turn it off. nor can I wire cables or use a computer. work around is to alt click and click it in the list.

**Comment by nullbear** [comment]
my suggestion is for the overlay, just set the opacity/sprite of the object, the object does not need to store any other information about the atmosphere.

**Comment by lmas** [comment]
As with the old phoron bug just make the gas be able to be clicked through, by changing the opacity or what was done back then. No need to complicate it.

Edit: See https://github.com/stuicey/ApolloStation/issues/4

**Comment by lmas** [comment]
Did some testing just now and don't have any problems with any gas overlays.
