### ISSUE TITLE
Mining Outpost Woes

### ISSUE THREAD

**Issue by Draco16** [Apollo-Community/ApolloStation#138]
- [x] T he airlock starts each round depressurized and unbolted so any miner who touches the door causes it to open and depressurize the entire room.  
- [x] The button for opening the interior airlock is now missing every round, and miners can't open the airlock from the inside if it is locked.  
- [x] After scouring a good portion of the asteroid with the scanner I can declare that the asteroid is is void of core materials for the drill heads to mine.  Either that or the scanners are broken.
- [ ] EDIT: the conveyor system leading outside is missing a bend so crates can't make it back outside without getting stuck

**Comment by lmas** [comment]
- [ ] Mining airlock get stuck trying to cycle the room. still.
- [ ] Poor camera coverage on the mining portions of the ACE

**Comment by hexagoncode** [comment]
Was there an update during this time? The conveyor system to the left that leads to and from the furnace room depending on the direction successfully brings materials inbound.

The airlock seems to be made with airless tiles instead of standard tiles, so either the exterior door needs to be open to cycle inward or those tiles need replaced. I suggest replacing them because nobody starts outside anyway.

The airlock control seems to be back, but for the love of god, add more vents. That room is large and the cycle time takes forever.

**Comment by GeckoDragon** [comment]
the reason for the airless tiles in the airlock is because it was originally a ramp leading out into space with no doors between it and the rock. With the moving of the airlock into the "ramp" to improve the time taken for a complete airlock cycle, the flooring was never replaced and as such is always depressurised on round start.

**Comment by GutsySS13** [comment]
- [x] Research emitter doesn't work - still (2 july 2015)

**Comment by stuicey** [comment]
All the things in here seem to be functioning now.
