### ISSUE TITLE
Visitation area door in brig

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#152]
Is only opened with a button. Once a visitor goes inside and the door closes, he's trapped for good. A better idea is to give the door all access and remove the button or let it bolt the door.

**Comment by GutsySS13** [comment]
I think the whole point of prison visits is to be supervised, otherwise anyone could just bring in bombs or other contraband. Being able to get away without security knowing who dropped off what is a bit of a risk. If anything i'd say getting in and out should be restricted and possibly authorised by a sec officer, but maybe that's just me. You can always pull faces at each other through the glass in the hallway.

Just checked baystation and it looks like it's the same situation there too, access is 63 (security front doors) for the visitation window and visitation door.

But yeah looks like an oversight at the moment as is a bit of a trap as there's no way out unless released by an officer as there is no access control on the button.

**Comment by GutsySS13** [comment]
Hopefully now fixed, as I've moved the button and set the access to security, lets see if the image works here:

![sec foyer](https://github.com/GutsySS13/shared-stuff/blob/master/secfoyet2015-05-23.png)

it's getting a bit button mad in that room so i'd advise against putting one in for the prisoner side, they can come and go as they please anyway.

**Comment by lmas** [comment]
Alrigt good. But if theres so many buttons in there maybe it's a better
idea to remove it completely and just let security open the door manually.
But then they would have to leave the safe comfort of the brig chairs :p

**Comment by GutsySS13** [comment]
After  a mini discussion with Stuicey I've moved the button slightly and the main security doors as well.

Now all they need is a donut box and some privacy blinds (the fire alarm shutters only close the front windows) and they can relax in peace.

![Stupid Brig foyer picture should be here](https://github.com/GutsySS13/shared-stuff/blob/master/brigfoyer2015-05-25.png)
