### ISSUE TITLE
Spacepod fabrication console do not have upload or download rights within the R&D server room

### ISSUE THREAD

**Issue by GeckoDragon** [Apollo-Community/ApolloStation#159]
Although the fix has been made for searching within a local area for the terminal the terminal itself still doesn't have access rights

Bug reported by proxy by grant4455

**Comment by lmas** [comment]
The Upload/Download rights are toggled off by default, unlike the robotics lab and main R&D which is toggled on by default.

Edit: More digging. I think toggling the upload/download rights does nothing since there's no spacepod server, as this is stored as a var in a server obj. Robotics and R&D have each their own server, but there's not one for spacepods.
