### ISSUE TITLE
Mining asteroid runtime errors

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#240]
I presume that you guys are seeing this on your live server, but it seems that when the map is generating random rooms they seem to have an un-defined variable side_type that gives a ton of errors for every special asteroid room turf it tries to make.

> runtime error: undefined variable /turf/simulated/floor/var/side_type
> proc name: New (/turf/simulated/mineral/New)
>  source file: mine_turfs.dm,43
>  usr: null
>  src: the floor (77,180,6) (/turf/simulated/floor)
>  call stack:
> the floor (77,180,6) (/turf/simulated/floor): New()

This is probably making massive runtime log files so may need some attention soon.

**Comment by lmas** [comment]
For some reason `/turf/simulated/wall/r_wall` and `/turf/simulated/floor/engine` is leaking into the code at [/turf/simulated/mineral/New()](https://github.com/stuicey/ApolloStation/blob/00ebc9d354d993c88aca02c732faf61e19a91a12/code/modules/mining/mine_turfs.dm#L43).

Edit: It's because of the randomly created rooms on the asteroid. @Kwask you might need to make sure it's a mineral turf in that linked code.

**Comment by Kwask** [comment]
Fixed a while ago
