### ISSUE TITLE
Medical subgrid non-existant and subgrid APC's in wrong subgrids

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#259]
Basically subgrids are messed up. APC's are in the wrong subgrids (e.g. Dance Floor is in the engineering subgrid and MANY more) and the medical subgrid only gives a "# system error - no powernet #" error.

**Comment by GutsySS13** [comment]
It looks to me that there is an extra wire in medbay that creates a dot under the breaker box. also it's sensor doesn't have a wire dot under it. The basement sub-grid looks ok though with both breaker and sensor setup as the others on the station.

I'm no expert on these things but would suggest that the wire under the breaker needs moving and the sensor need 2 half wires so that it's connected by a dot, no ideas on the dance floor issue though.
