### ISSUE TITLE
Ghosts/observers can interact with the electric chair.

### ISSUE THREAD

**Issue by ghost** [Apollo-Community/ApolloStation#30]
Observers and ghosts can use the "toggle electric chair" option on the electric chair.

**Comment by lmas** [comment]
[Electric chair](https://github.com/stuicey/AS_Project/blob/master/code/game/objects/structures/electricchair.dm#L26)

And ghosts can rotate [shield capacitors](https://github.com/stuicey/AS_Project/blob/master/code/modules/shieldgen/shield_capacitor.dm#L144) inside the engineering storage.

**Comment by lmas** [comment]
There's more items that ghosts can interact with, [bunsen burners](https://github.com/stuicey/AS_Project/blob/master/code/modules/research/xenoarchaeology/tools/bunsen_burner.dm#L48) for example can be toggled.

The correct way to fix this is with a rewrite of the ghost code, I guess... Though for now it's easily fixed by adding checks for ghosts whenever someone finds yet another item they can interact with.

Ideas anyone?

**Comment by stuicey** [comment]
It's a common convention to setup attackby procs taking any derivative of /mob/_. When in most cases it should be var/mob/living/_. 

Though the easiest way to remedy is to just add a mob.stat check on the procs in question.

**Comment by stuicey** [comment]
known issues fixed in 75fc61692e6bcf5406c6bcecae4e892aeeb01994

**Comment by Fleegle2000** [comment]
Is there a reason this is still open?

**Comment by stuicey** [comment]
There are lots of other items that have a similar issue as the one described that haven't been discovered yet.

**Comment by stuicey** [comment]
Just going to close this and it can be addressed on a case-by-case basis
