### ISSUE TITLE
Stacking machine issues

### ISSUE THREAD

**Issue by mewseht** [Apollo-Community/ApolloStation#409]
The stacking machine on the ACE holds finished materials inside it until it reaches a specific point at which it dispenses said materials in stack. The problem is that steel is not being "held on to" but is instead just spit right out as a single sheet. This is not a problem for any other material.

**Comment by Kwask** [comment]
Since the name of "metal" was changed to "steel", I bet the stacking machine doesn't know what to do, and so it just spits it out without stacking.

**Comment by lmas** [comment]
There's a lot of these in the log:

```
TESTING: GC: -- /obj/item/stack/sheet/metal was deleted via del() rather than qdel() --
```

Edit: Btw, only the [name of the object was changed](https://github.com/Apollo-Community/ApolloStation/blob/master/code/game/objects/items/stacks/sheets/sheet_types.dm#L96). I did a grep on the code and found about 286 matches for `"metal"` (a lot of `if("metal")` lines), so that's a lot of other broken stuff that depends on the old metal name... paging @nullbear. How should we handle this now, proceed and fix all those faulty lines in the code or revert the name change?

**Comment by nullbear** [comment]
Just revert the name change from steel to metal for now. I'll go through the code myself and fix all the name dependency issues when i finish the materials.

Didn't realize there was a dependency on the name at the time.

**Comment by lmas** [comment]
Yeah, with the horrible state of ss13 code in general and it's size it's
understandable that one can't catch problems with any new code. Especially
with hardcoded stuff.
That's why I haven't done any major changes and am just fixing teeny tiny
bugs.

I'll go ahead and revert the name for you then, tomorrow.

Besides this bug people, including me, seems to like the new sheet icons so
well done with that at least ;)

**Comment by nullbear** [comment]
yay xD I was actually a fair bit worried about that.

**Comment by nullbear** [comment]
They feel a bit too big for me tbh though. Like... they're massive. And i guess that's fine when it takes 2 sheets to build a wall.

**Comment by lmas** [comment]
Stacking works again. Feel free to update the hardcoded stuff, then we can revert my quickfix in the future.
