### ISSUE TITLE
Double-clicking on sleepers and scanners to enter/eject

### ISSUE THREAD

**Issue by Fleegle2000** [Apollo-Community/ApolloStation#50]
It would be helpful if one could enter or exit a sleeper or scanner simply by double-clicking on it.

**Comment by lmas** [comment]
Each machine that has a move_inside() verb could be given this new function:

```
attack_hand(mob/user as mob)
    if (src.occupant == usr)
        eject()
    else
        move_inside()
```

That would allow the player to simply click on the machine to enter it. This also works correctly when the player has grabbed another mob (as in, the grabbed mob would be put inside instead of the player himself). There's a bunch of machines that needs to be updated though.. 

If no one has any objections I could make a new PR.

**Comment by Kwask** [comment]
You'd want to make sure that it checks if there's an occupant first, so the person administering the treatment doesn't snuggle up next to their patient on accident. Also, a short delay similar to what it takes to put someone inside would be good, so if someone accidentally clicks it, they have time to move away.

Other than that, I'd be happy to have this in :baby:

**Comment by lmas** [comment]
That's already implemented in the [move_inside() verb](https://github.com/stuicey/AS_Project/blob/master/code/game/machinery/Sleeper.dm#L406).

**Comment by lmas** [comment]
Made the changes on the machines. I'm not sure I like this though. Usually clicking on a machine means it should pop up it's control interface if it has one. This change breaks that somewhat standard behavior and might confuse players.
