### ISSUE TITLE
New event for when an atmos tech is on

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#537]
How about a new event for atmos tech's to deal with: Phoron leak.

Maybe have a very small phoron/sleeping gas leak somewhere (maybe just 1% of the air volume or something for phoron, 5% for sleeping gas). it could either choose a random area, or maybe better a pre-set list of 20 or so rooms where it can happen. That being said a lot of the air siphons are now set to automatically scrub nasties and it think it should be reverted back (just because people are lazy doesn't mean they should get an 'i win' button).

Virologists get viruses, engineers get meteors so why not atmos tech's?

ps. I still think atmos and engineering should be merged as there's hardly any atmos techs these days but still think this could be an event type for them as they need something to do (read un-set automatic filtering of bad stuff). 

pps. I also think we should revert power usage for pumps and stuff as it's pretty ridiculous the power usage of these things and also stops people wanting to play atmos as you can't do jack.

**Comment by halworsen** [comment]
The scrubbers should be scrubbing for bad gases automatically, IMO. Nobody will ever have the patience or time to set up every single air alarm on the station for it. It'd be much better if the event changed the air alarm settings and then added the bad gases.

Also, I firmly believe atmos tech should be kept as an individual job. Pipes and gases are such a large part of engineering that it warrants its own job. Merging it with engineering would end up with engineers being a do it all & know it all job, much like scientists, who do R&D, toxins, xenoflora, xenoarch, and pretty much anything to do with science.

**Comment by Kwask** [comment]
Ehh. I dont like this. It'd be better if it was something more like pipe bursts. (also shh, the virologists making virus spawns is secret)

Also, to reply to atebite, while atmospherics is substantial in size, its very much a part time job. There's just nothing for an atmos tech to do during a round except fix an occasional breach

**Comment by lmas** [comment]
I'm agreeing more with atebite on this, but i still think it's a good suggestion.
Let the scrubbers be filtering automagically and keep it as a separate job, but add in one or a couple of events that would "burst a pipe" (drains a room of all gases), "leak out phoron gas in a room" or "faulty pumps increasing pressure in a room", and stuff like that, and only run them when there's an active atmos tech around.

Also kwask, there's a bunch of other jobs that have as less things to do, like the chaplain, entertainer and librarian. I think just because they don't have anything to do they shouldn't be merged into another job (maaybe, I haven't been thinking much of it yet..). If you're going to merge atmos/eng you might aswell merge the others too, into in some way.

**Comment by Kwask** [comment]
Chaplain, entertainer, and librarian are all roleplay roles, though, which atmos is not. Atmos is largely a role for gameplay, but it lacks any sort of real content to justify it.

Also, it's been talked about for a long time that a large number of roles would be absorbed into one another.

**Comment by lmas** [comment]
Then in that case, I guess you could compare atmosia with chemistry instead, as they are less RP/more gameplay just like atmos too. I get the feeling we're going to have to make yet another refactor and clean up the jobs too :D

**Comment by nullbear** [comment]
should be possible to set default air alarm settings from the computer, and setting room air alarm settings to use different templates, at the push of a button. I've seen it a few places, but i think we could do better.

Ie. 'vox', 'server' and 'normal' rooms are things i've seen where you just push the button and the air alarm is set to the template.

Obviously because of griefy potential it should have an alert on it, that alerts head of staff and admins when someone mass-alters a template. And SoP saying you need to have a CE's permission to use the computer like that, or just ce level access on the computer.

otherwise, using the computer is sooooo slowwwww you do it one room at a time and to change any settings to scrub toxins takes half a minute for each air alarm, and you have massive alarms going all across the primary hallway.

**Comment by lmas** [comment]
Moved to https://apollo-community.org/viewtopic.php?f=10&t=667
