### ISSUE TITLE
Some books may have links to old baystation wiki.

### ISSUE THREAD

**Issue by GutsySS13** [Apollo-Community/ApolloStation#64]
Someone reported:

Request for Help:: Disco Bacon/(Greg Burdette): The space law books need to be fixed.

Apparently they are pointing to the old wiki pages instead of the new ones. since baystation changed their domain a short while ago, it may be worth while running a search and replace to find any old links still around.

Have a search for: 
baystation12.net/wiki
and replace it with
wiki.baystation12.net

**Comment by Fleegle2000** [comment]
I'll check it out.

**Comment by stuicey** [comment]
It is not as simple as this, the manuals use the wiki url supplied as a config variable. The issue is that the new wiki does not have the same pages as the previous one. 
For example, you used to append &printable=yes&remove_links=1 to the corporate regulations page which would return a version suitable for SS13

**Comment by Fleegle2000** [comment]
Yes that appended bit is still in the code. The new Corporate Regulations is http://wiki.baystation12.net/index.php/Corporate_Regulations.

**Comment by stuicey** [comment]
Already changed it on my local repo, will leave issue open as it is by far from a good solution.

**Comment by hexagoncode** [comment]
Same thing seems to be happening with "Engineering Textbook" in the engineering section.
