### ISSUE TITLE
Can't push things down stairs

### ISSUE THREAD

**Issue by lmas** [Apollo-Community/ApolloStation#65]
Stuff like closets will block the stairs down. Pushing things up works though.

**Comment by Fleegle2000** [comment]
I'll take a look at this. I remember looking at the stairs code when I fixed the bug with drones not being able to go up stairs. If I recall correctly the issue is that stairs only let a small subset of things through, though I'm not sure why you can push stuff up them but not down them.

**Comment by JMMJ01** [comment]
I think the issue is when it warps it doesn't move of the tile is the
reason it blocks. Pushing through doesn't have the moment to sail like
throwing a body through.

**Comment by Kwask** [comment]
One way we could try to remedy dense objects blocking stairways is by making dense objects tumble down the stairs. So when an object enters a turf with stairs, it would check if the object is dense, and if it was, it'd tumble down the stairs. Makes sense because pushing a closet down the stairs isn't exactly elegant

**Comment by JMMJ01** [comment]
That could work, but pushing up would be an issue the , since if you want
the realistic way, you can't just push one upstairs, either. Possibly the
tumbling or changing for when they hit a tile just having them move through
it and into the next would make it so they didn't block.

**Comment by lmas** [comment]
Realistic wouldn't be any fun in this case. A griffin could easily trap people downstairs by blocking the stairs and the poor sods down there can't push things back up again. 

The stairs is a really nasty bottleneck for movement, since the only way to move through it is by the stairs themselves. No way to go around them (by breaking down walls for example). You block the stairs, you're trapped for good.

I say if an object can be moved (ie, not bolted to the floor), one should be able to push it up/down the stairs.

**Comment by Kwask** [comment]
The issue is that currently, if a dense object is sitting on a staircase lower than you, you cannot push it out of the way because you instead just stand on top of it. As far as I'm aware, there's no proc to check behavior liked this.

Also, as far as the griffin is concerned, if you're the one trapped at the bottom of the staircase, just move the object out of the way and walk up the stairs like normal :P

**Comment by Fleegle2000** [comment]
So I discovered, apparently this bug also affects slimes. Maybe I was just doing it wrong. I was disappointed that I couldn't go dancing with my pet slime.

**Comment by lmas** [comment]
Hey @GutsySS13, @Nullbear, were you guys not discussing this thing last week in some form? How did that go?

**Comment by nullbear** [comment]
The issue is caused by objects on the bottom step being bumped from z+, rather than y/x on the same zlevel. A simple hacky fix is to change it so that you change z levels on the top step as you exit it, before sliding sideways. Alternatively you could just teleport the person to the tile. Skipping 'move' altogether

**Comment by stuicey** [comment]
Just tested this and was able to push and pull movable objects up and down stairs.
