### ISSUE TITLE
Wiki (again)

### ISSUE THREAD

**Issue by Awantje** [Apollo-Community/ApolloStation#76]
I cannot do this with my permission but can an admin.
make all these pages moderated:
http://wiki.apollo-community.org/index.php?title=Category:Moderated_Pages
Perhaps even the main page.
And can they remove these pages (they are doubles or wierd redirects):
http://wiki.apollo-community.org/index.php?title=ThatOneGuy:Religion&redirect=no
http://wiki.apollo-community.org/index.php?title=Ravensdale_rules&redirect=no
(more will come later)

**Comment by Fleegle2000** [comment]
I would also like to propose removing the NSS Exodus page, since it is not part of our lore (I think?). Or if it is, we should have a page for the NSS Apollo.

Edit: Same goes for much of the lore pages - I assume most of that (which is outdated even for Bay) is going to be changing. Might want to just do a purge of many of those pages. I'm not sure what Apollo is currently using as a lore bible.

**Comment by Kwask** [comment]
Made those pages protected. Also, from now on you shouldn't use the bug tracker for the wiki. This is for game use, not the wiki :P

If you want to report issues, post it on the discussion page for the offending article

**Comment by Fleegle2000** [comment]
Fair enough.
