### ISSUE TITLE
Antag issues

### ISSUE THREAD

**Issue by CakeQ** [Apollo-Community/ApolloStation#999]
- [x] Notoriety does not go up
- [x] Persistent antags can't pick factions
- [x] Persistent antag tokens don't make people persistent antags

**Comment by CakeQ** [comment]
- [x] Antags have contracts in extended

**Comment by halworsen** [comment]
Need more info on some of these. How many contracts were completed, and what was the player's notoriety when they reported it not going up? Did they get a message that it did?

Especially need info on the token thing. Can you play the round you redeem the token, but not the one after, etc.

**Comment by CakeQ** [comment]
Player's notoriety was at 0 and they had completed a lot of objectives, all the while being a pers. antag.
Token redemption doesn't work directly during the round you redeem it as well as future rounds. I don't think anyone has ever gotten a message regarding notoriety increase (I didn't even know that was a thing)

**Comment by halworsen** [comment]
Did they save their character after using the token?

**Comment by Kwask** [comment]
Why wouldn't it save the character automatically if it saves the tokens automatically?

**Comment by halworsen** [comment]
Tokens are tied to the client, antag data is tied to the character. Characters aren't saved when you use command tokens either, and I think that's a weakness with how characters are saved at the moment, because the first time you save it, you're locking in name, age, etc.

If we saved the character automatically, it could happen that we lock in character traits before the player was done changing the character name and stuff.

**Comment by Kwask** [comment]
I think that's less of a concern than someone losing their antag token because they were never informed that they had to save.

**Comment by halworsen** [comment]
Alright, I'll be adding automatic character saving when you use character tokens, then.

**Comment by halworsen** [comment]
See if tokens are fixed now (b1cb3b9 & 6a83730)

**Comment by halworsen** [comment]
Everything should be fixed. Reopen if stuff's still broken.
